<?php
$source_version='6000';
$cache_version='2.0.4';
$properties=array(
'browser_name',
'browser_name_regex',
'browser_name_pattern',
'Parent',
'Comment',
'Browser',
'Browser_Maker',
'Version',
'MajorVer',
'MinorVer',
'Platform',
'Win32',
'Win64',
'isMobileDevice',
'isTablet',
'Device_Type',
'Device_Pointing_Method'
);
$browsers=array(
'a:13:{i:4;s:17:"DefaultProperties";i:5;s:17:"DefaultProperties";i:6;s:7:"unknown";i:7;s:3:"0.0";i:8;s:1:"0";i:9;s:1:"0";i:10;s:7:"unknown";i:11;s:5:"false";i:12;s:5:"false";i:13;s:5:"false";i:14;s:5:"false";i:15;s:7:"unknown";i:16;s:7:"unknown";}',
'a:7:{i:3;i:0;i:4;s:15:"Default Browser";i:5;s:15:"Default Browser";i:11;s:5:"false";i:12;s:5:"false";i:13;s:5:"false";i:14;s:5:"false";}'
);
$userAgents=array(
0=>'DefaultProperties'
);
$patterns=array(
'@^.*$@'=>1
);
